import { LOGIN_LOADING, LOGIN_SUCCESS, LOGIN_FAILURE } from './LoginAction';
import { REGISTER_LOADING, REGISTER_SUCCESS, REGISTER_FAILURE } from './RegisterAction';

export {
    LOGIN_LOADING,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTER_LOADING,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
};